In [4]:
import pandas as pd
import array


def view_model(model):
    """
    Look at model coeffiecients
    """
    print (model.coef_, model.intercept_)


input_file = "QUES.csv"
input_file2 = "UIMS1.csv"

# comma delimited is the default
df = pd.read_csv(input_file, header=0)
df2 = pd.read_csv(input_file2, header=0)

# put the original column names in a python list
original_headers = list(df.columns.values)
original_headers2 = list(df2.columns.values)
# print (original_headers)

# remove the non-numeric columns
df = df._get_numeric_data()
df2 = df2._get_numeric_data()
# put the numeric column names in a python list
numeric_headers = list(df.columns.values)
numeric_headers2 = list(df.columns.values)



In [5]:
import numpy as np
# create a numpy array with the numeric values for input into scikit-learn
numpy_array = np.asmatrix(df)
numpy_array2 = np.asmatrix(df2)

# numpy_array = np.concatenate((numpy_array,numpy_array2))

# print (numpy_array)

X = numpy_array[:, 0:10]
Y = numpy_array[:, 10]

from sklearn.linear_model import LinearRegression

clf = LinearRegression()

training_features = X
training_labels = Y

In [7]:
#training_features = [x for (y,x) in sorted(zip(Y,X), key=lambda pair: pair[0])]
#training_labels = [y for (y,x) in sorted(zip(Y,X), key=lambda pair: pair[0])]
k=0;
for i in training_labels :
    print (training_features[k] , training_labels[k])
    k=k+1
k=0;
for i in training_labels :
    print (training_features[k] , training_labels[k])
    k=k+1
#k=0;
#for i in training_labels :
#    print training_features[k] , training_labels[k]
#    k=k+1
#print (training_features)


[[  0   0   2  27   5   1  38  24  25 365]] [[102]]
[[  2   0  18  39   3   2   4   5   9 174]] [[85]]
[[  2   0  11  29   4   1   2   5   7 122]] [[38]]
[[  2   0  20  96  26   5  28  31  36 485]] [[81]]
[[  2   0   8  62  10   8  31  29  37 310]] [[55]]
[[  2   0  27 150  19  12  60  35  49 648]] [[101]]
[[  2   0  14  68  18   5  14  25  31 260]] [[38]]
[[  2   0  38  59   4   1   2   5   7 365]] [[157]]
[[  2   0  18  86  14   8  23  23  32 376]] [[68]]
[[  2   0  24  40   4   2   2   5   8 144]] [[26]]
[[  2   0   8  54  14   4  13  19  24 211]] [[24]]
[[  2   0  18  38   4   1   2   5   7 230]] [[86]]
[[  1   0  10  22   4   0   7   4   4 121]] [[26]]
[[  2   0  13  68  14   3  17  18  23 245]] [[47]]
[[  2   0  16  32   4   1   2   5   9 174]] [[78]]
[[  2   0  23 110  18  14  48  38  53 534]] [[88]]
[[  2   0  20  41   5   1   2   6  10 250]] [[124]]
[[  1   0  12  22   4   0  13   4   4 172]] [[28]]
[[  2   0  13  22   3   1   2   4   8 142]] [[62]]
[[  2   0  16  42   5   3  

In [9]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
clf = LinearRegression()
clf.fit(train_in, train_out)
sc = clf.predict(test_in)
sc_up = (test_out - sc)/71
err = sum(sc_up)
print (err)
sc = clf.predict(training_features)
#print "printing scores" , sc
import math
k=0;
for i in sc :
    #print training_labels[k] - sc[k]
    #sc[k] = (i-trainii-training_labels[k]ng_labels[k])**2
    sc[k] = math.pow(i-training_labels[k], 2)
    print (k ,  sc[k])
    k=k+1;
from sklearn.metrics import r2_score,mean_squared_error
print (r2_score(training_labels,sc))
print (mean_squared_error(training_labels, sc))
#print sc
#print training_labels
view_model(clf)
##
index = []

NameError: name 'train_in' is not defined